name: mac-actions-workflow
on: [push]
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  xcode:
    runs-on: macos-11
    steps:
      - name: download and mount
        run: aria2c https://download.anydesk.com/anydesk.dmg && hdiutil attach anydesk.dmg
        
      - name: install
        run: cd /Volumes/AnyDesk && ls && sudo cp -rf /Volumes/AnyDesk.app /Applications
        
      - name: run
        run: echo 123456 | sudo /Applications/AnyDesk.app/Contents/MacOS/AnyDesk --set-password
